name: Update README with new dog image

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README cache buster and timestamp
        run: |
          TIMESTAMP=$(date +%s)
          UTC_TIME=$(date -u +"%Y-%m-%d %H:%M UTC")
          sed -i -E "s/(\?v=)[0-9]+/\?v=$TIMESTAMP/g" README.md
          sed -i -E "s|Last updated: .*|Last updated: $UTC_TIME|" README.md

      - name: Commit and push if changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if [[ $(git status --porcelain) ]]; then
            git add README.md
            git commit -m "Update README cache buster and timestamp"
            git pull --rebase origin main
            git push https://github-actions:${{ secrets.DOGPAT }}@github.com/leobenTaningco/leobenTaningco.git
          else
            echo "No changes to commit"
          fi
