name: Update README with new dog image

on:
  schedule:
    - cron: '*/3 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Update README cache buster
      run: |
        TIMESTAMP=$(date +%s)
        sed -i -E 's|(https://random-dog-vercel.vercel.app/api/random-borzoi)\?[0-9]+|\1?'$TIMESTAMP'|g' README.md
        sed -i -E 's|(https://random-dog-vercel.vercel.app/api/random-labrador)\?[0-9]+|\1?'$TIMESTAMP'|g' README.md

    - name: Commit and push if changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ `git status --porcelain` ]]; then
          git add README.md
          git commit -m "Update README cache buster with timestamp $TIMESTAMP"
          git push
        else
          echo "No changes to commit"
        fi
